### PR TITLE
Translate Readme.md to Portuguese.

### PR DESCRIPTION
**Pull request by thiagoponte**

### CODE REVIEW

**Comment by sararosso** [comment]
Just clarifying, is this Brazilian Portuguese? It should be in a pt-br folder if so.

**Comment by thiagoponte** [comment]
Yes it is Brazilian Portuguese.
Should i close this PR and make another one?

**Comment by greguly** [comment]
Olá Thiago.

**Comment by greguly** [comment]
I think we don't need to translate the readme.md but isntead the actual document.

Just like it was done here: https://github.com/Automattic/Documattic/tree/master/WordPress-Security-White-Paper/fr

**Comment by thiagoponte** [comment]
I've renamed the folder to pt-br, deleted the translated Readme.md and started the translation of the actual document.

**Comment by greguly** [comment]
Fantastic! 

Conheces o http://traduza.wp-brasil.org/? 

Lá tem um glossário para orientar como devemos traduzir alguns termos. ;-)

**Comment by thiagoponte** [comment]
Não,  obrigado pela dica.  Vou ler e seguir as orientações.

**Comment by greguly** [comment]
Legal.

Aproveita e te apresenta lá, sempre precisamos de tradutores e validadores para as traduções do WordPress.

Eu ajudava montando os pacotes, mas agora isto está automatizado.

**Comment by sararosso** [comment]
Hi there! Thanks for your feedback - we've moved the white paper over to the WordPress repo, so we'd really love this to be re-submitted there! Thanks :) 
https://github.com/WordPress/Security-White-Paper

**Pull request closed without merging**
